# Generated by Django 4.1.4 on 2022-12-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theater_ticket",
            fields=[
                (
                    "theater_ticket_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
            options={
                "db_table": "movie_theater_tickets",
            },
        ),
    ]
