# Generated by Django 4.1.4 on 2022-12-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.TextField()),
                ("address", models.TextField()),
                ("detailed_address", models.TextField()),
                ("phone", models.TextField()),
            ],
            options={
                "db_table": "shop_deliveries",
            },
        ),
    ]
