# Generated by Django 4.1.4 on 2022-12-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                ("view_id", models.AutoField(primary_key=True, serialize=False)),
                ("ip_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blog_views",
            },
        ),
    ]
